### ISSUE TITLE
Inpit resolution syntax

### ISSUE THREAD

**Issue by mozo78** [hamidzr/webcam-mods#17]
Hello,
I'm sorry but I really can't figure out what should be the syntax for setting Inpit resolution. I tried in terminal:
`export IN_WIDTH=1920 IN_HEIGHT=1080`
but it gives me the same 640x480 output. The main problem is Teams is getting only a part of the image (upper left corner), expands it to fit the camera and the image gets pixelated because of the lower resolution. Or may be it's the output resolution? I don't know but I want it to show the whole image at the original resolution.
Can you help me with this? I'll be very grateful!

**Comment by hamidzr** [comment]
hey @mozo78 which option are you using through the cli? `python entry.py --help`
 the tool also supports dynamic cropping that you can interactively control while the camera is running maybe that's what is limiting your output? I gotta run but I'll take another look later.

**Comment by mozo78** [comment]
Thanks for your answer @hamidzr, really appreciated!
I use the following command:
`cd "`dirname "$0"`"/webcam-mods-master && pipenv run echo "1234" | sudo -S make add-video-dev
pipenv run python entry.py bg-swap`
This problem is critical for me because I migrated all my coleagues to Linux over time (~30 people) and now lack of custom image setting in Teams for Linux may lead to return them to Windows which is very very sad :( I really want to know how to control the resolution to avoid returning to Windows.

**Comment by hamidzr** [comment]
I got some time today and tomorrow to look into this. let's put the issue with only getting a part of the background image when you use `bg-swap` aside. that's a known issue that I don't have an immediate solution for but blur should work fine.
two potential issues with input resolution:

1. you're not using the correct settings
2. webcam and webcam driver limitations

**Comment by hamidzr** [comment]
> webcam and webcam driver limitations

as this tool is set up we take raw pixel data from the camera  (`YUYV`) and webcams usually push those at a lower resolution for a given FPS compared to compressed formats such as MJPEG. 
[formats.txt](https://github.com/hamidzr/webcam-mods/files/7697941/formats.txt)

technically we should be able to work with those other compressed formats as well but currently we don't support that. I can look into how much work that is. opencv probably does most of the heavy lifting.

**Comment by hamidzr** [comment]
also when you start the script it prints out what configuration it's working with. sharing that would help too

```
starting with config {'crop_dims': [864, 480], 'crop_pos': [0, 0], 'pad_size': [0, 0]}
begin passing from #Webcam to #VirtualCam
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
input: {'width': 864, 'height': 480, 'fps': 24.0}, output: {'device': '/dev/video10', 'width': 320, 'height': 240, 'fps': 24.0}
```

**Comment by mozo78** [comment]
Thanks for your answer!
Yes, both blur and bg-color are working fine. I don't know if the resolution is the culprit for taking just a part of the image, it's my wild guess.
I can't give you a log today for they are coleagues laptops and today is Sunday. I can take it tomorrow if it's still required :)

**Comment by hamidzr** [comment]
I added support for different webcam input formats in 39db969ee3f4f4ab23d3e4e14ad160c377869570 and 6a58df1c384ae89c80fac5a509ac58fe76c2ca93 and added an env variable to make the output resoultion configurable. 

I currently set these options as env var for my own setup on one of my machines

```
# export PYTHONPATH="./src:$PYTHONPATH"
export ON_DEMAND=True
export VIDEO_IN=0
export MAX_OUT_FPS=30 # 20
export IN_WIDTH=1280
export IN_HEIGHT=720
export IN_FORMAT=MJPG
```

**Comment by mozo78** [comment]
This are very cool options, thank you!
Does this help with the partialy taken image?
And when I shoud export these options - when prepare the project or with every start?

**Comment by hamidzr** [comment]
glad to help. these should be present in the env your script runs every time. I use direnv  https://github.com/direnv/direnv to set project-specific env values.

no these wouldn't help with the partially taken image (if you mean the background image for bg-swap). that's works for another time.

**Comment by hamidzr** [comment]
checkout `./src/config.py` and `--help` for more options

**Comment by mozo78** [comment]
> no these wouldn't help with the partially taken image (if you mean the background image for bg-swap). that's works for another time.

Let's hope it'll be sooner than later :)

**Comment by hamidzr** [comment]
can you confirm if the resolution issue is fixed? if so I'll close this issue. Feel free to open another one for the background image feature

**Comment by mozo78** [comment]
I can try for we are in Chrismas vacation. The general problem is the partial image so we can assume this as fixed :)
