### ISSUE TITLE
ModuleNotFoundError: No module named 'webcam_mods'

### ISSUE THREAD

**Issue by andreas-it-dev-llc** [hamidzr/webcam-mods#25]
Hi,

first of all: i am not really a python guy, though i found your software to get bg blurring working on linux.

when trying to kinda reverse engineer how to actually start the whole thing i end up with this situation:

```
(webcam-mods) [andreas@world-hq webcam_mods]$ pipenv run python entry.py bg-swap
Traceback (most recent call last):
  File "entry.py", line 2, in <module>
    from webcam_mods.config import DEFAULT_BG_IMAGE
ModuleNotFoundError: No module named 'webcam_mods'

```

its probably me who does something horribly wrong, could you please shed some light onto how to get it running?

**Comment by hamidzr** [comment]
hey a while back I switched how you install and use the tool. now you'd want to install it as a package. I'll try to write down the steps as I recall them. I won't have my Linux machine available for a while.

- use pipenv to create a virtual env and install the dependencies 
- install this package from source: from the virutal env and the root directory of this repo do `pip install -e .`
- now you should have an executable called `webcam_mods` and you can run it with `webcam_mods --help`
- make sure to create the virtual video device necessary. there is a make target for it

**Comment by hamidzr** [comment]
it's been a while I'll close this out. feel free to reopen
