### ISSUE TITLE
More Detailed Installation Instructions

### ISSUE THREAD

**Issue by antintin0** [hamidzr/webcam-mods#6]
This project looks great, but it would be great if you could add in step-by-step installation instructions for complete noobs!

**Comment by afedulov** [comment]
+1 I would like to give it a try, but do not have time to figure out the setup. Some basic requirements and first steps would be great to have (pipenv etc.)

**Comment by hamidzr** [comment]
I'll have a go at this. what operating systems are you using? I can only test this on Arch Linux.

**Comment by antintin0** [comment]
> I'll have a go at this. what operating systems are you using? I can only test this on Arch Linux. Any specific steps that are the most confusing?

I think instructions for debian/ubuntu based distros would be the most useful as the most noobs use those (including me lol)

**Comment by pezhore** [comment]
Adding to this - if you have more than one webcam (e.g. a built-in laptop cam and an external/USB cam) how do you specify which source device to use?

**Comment by hamidzr** [comment]
> Adding to this - if you have more than one webcam (e.g. a built-in laptop cam and an external/USB cam) how do you specify which source device to use?

if you have you know what ID the video device you're using has you can provide that using `VIDEO_IN` environment variable eg `/dev/video0` . ref https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/

I have a few lines which either uses that or find the first available camera and sets that as the input device [here](https://github.com/hamidzr/webcam-mods/blob/5d5f42cbb0e645f1cac4c890afa66804c6e9dfe9/src/loopback.py#L21-L36)

you can play from a video device using `ffplay` eg `ffplay /dev/video10`

**Comment by hamidzr** [comment]
I recorded a quick [screencast here](https://youtu.be/idp7ei-pF40) there are a lot of pauses that could be edited but I'm lazy so feel free to skip forward and backward.

**Comment by hamidzr** [comment]
- added guidance on how to run and configure the different modes by adding cli arguments to `entry.py` using https://typer.tiangolo.com
- updated the README with available settings and modes
