### ISSUE TITLE
loopback problem

### ISSUE THREAD

**Issue by gaydenko** [hamidzr/webcam-mods#8]
HI! I have got:

```
❯ python src/uses/entry.py --help                                                                                                                   ±[master]
Traceback (most recent call last):
  File "src/uses/entry.py", line 1, in <module>
    from loopback import live_loop
ModuleNotFoundError: No module named 'loopback'
```
After 

```
❯ pip install loopback 
```
I get
```
❯ python src/uses/entry.py --help                                                                                                                   ±[master]
Traceback (most recent call last):
  File "src/uses/entry.py", line 1, in <module>
    from loopback import live_loop
ImportError: cannot import name 'live_loop' from 'loopback' (/home/user/.local/share/virtualenvs/webcam-mods-LF416mUB/lib/python3.7/site-packages/loopback/__init__.py)
```
Before following installation instructions I just have installed Python 3.7 from AUR (Manjaro).

**Comment by hamidzr** [comment]
that `loopback` an internal module located in `src/loopback.py` not a package you'd find on pypi. I have instructions on how to get python to pick that up in the [readme here](https://github.com/hamidzr/webcam-mods#installation) . 

I probably should update the import so it doesn't require this change 🤔 . If someone has more python experience.. is there a best practice here I should follow regarding how imports are organized?

**Comment by gaydenko** [comment]
Yes, I have missed that export, thanks! Then I was able to start with bg-blur, but it was just once. Next ateempts result in 
```
...
RuntimeError: 'v4l2loopback' backend: No v4l2 loopback device found at /dev/video[0-99]. Did you run 'modprobe v4l2loopback'? See also pyvirtualcam's documentation.
```
At the same time:
```
❯ v4l2-ctl --list-device                                                                                                                            ±[master]
Virtual01 (platform:v4l2loopback-000):
	/dev/video2`
...
```

**Comment by hamidzr** [comment]
You're welcome.

Yeah, I still have to figure this out but since I started using
`pyvirtualcam` everytime the program stops it removes the loopback device.
I looked into disabling the cleanup hook for it to see if I can get to stop
that but it didn't work out as I expected. It would need more work. For the
time being you'd need to add the device every time, eg `sudo make`
